<form class="form-signin" action="<?= URL_ADMIN ?>home/login" method="POST">
    <img class="mb-4" src="<?=IMG?>logo_grande.png" alt="" width="77" height="77" style="margin-left: 16px;">
    <img class="mb-4" src="<?=IMG?>LogoTransparent.png" alt="" width="119" height="119">
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>

    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="text" id="inputEmail" name="username" class="form-control" placeholder="Email address" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" value="remember-me"> Remember me
        </label>
    </div>
    <button class="btn btn-lg btn-block" type="submit">Sign in</button>

    <p class="mt-5 mb-3 text-muted">&copy; 2017-2020</p>
</form>