version: "3.1"
services:
        www:
#                image: pedromellob1/fwapachephp:latest
                build:
                        context: .
                        dockerfile: Dockerfile
                ports:
                        - "${APPLICATION_PORT}:80"
                volumes:
                        - ${APPLICATION}:/var/www/html/
                links:
                        - db
                networks:
                        - default
                labels:
                        - "com.docker.aws.lb.arn=arn:aws:acm:eu-west-1:417013183827:certificate/9b183535-55fc-45fa-afc5-4be428487b57@443"
        db:
                image: mysql:8.0
                restart: always
                ports:
                        - "${MYSQL_PORT}:3306"
                environment:
                        MYSQL_DATABASE: ${MYSQL_DATABASE}
                        MYSQL_USER: ${MYSQL_USER}
                        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                command: 
                        - --default-authentication-plugin=mysql_native_password
                volumes:
                        - ${MYSQL_DUMP}:/docker-entrypoint-initdb.d/dump.sql
                        - ${MYSQL_CONF}:/etc/mysql/conf.d
                        - persistent:/var/lib/mysql
                networks:
                        - default
        phpmyadmin:
                image: phpmyadmin/phpmyadmin
                links:
                        - db:db
                ports:
                        - "${PHPMYADMIN_PORT}:80"
                environment:
                        MYSQL_USER: ${MYSQL_USER}
                        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        grunt:
                image: pedromellob1/fwgrunt:latest
#                build:
#                        context: .
#                        dockerfile: Dockerfile
                links:
                        - www
                volumes:
                        - ${GRUNT_PATH}:/usr/src/project
                        - ${GRUNT_TARGET_PATH}:/usr/src/project/out/
                working_dir: /usr/src/project
#                command: bash -c "grunt-init ./boilerplate --force && npm install && grunt"
                command: bash -c "grunt"
        mdbook:
                container_name: mdbook
                image: peaceiris/mdbook
                stdin_open: true
                tty: true
                ports:
                        - ${DOC_PORT}:3000
                        - 3001:3001
                volumes:
                        - ${DOC_PATH}:/book
                command:
                        - serve
                        - --hostname
                        - '0.0.0.0'
        gruntadm:
                image: pedromellob1/fwgrunt:latest
                #                build:
                #                        context: .
                #                        dockerfile: Dockerfile
                links:
                        - www
                volumes:
                        - ${GRUNT_ADMIN_PATH}:/usr/src/project
                        - ${GRUNT_ADMIN_TARGET_PATH}:/usr/src/project/out/
                working_dir: /usr/src/project
                #                command: bash -c "grunt-init ./boilerplate --force && npm install && grunt"
                command: bash -c "grunt"
#        gruntadm:
#                build:
#                        context: ./grunt
#                        dockerfile: Dockerfile
#                links:
#                        - www
#                ports:
#                        - "${GRUNT_PORT}"
#                volumes:
#                        - ${GRUNT_ADMIN_PATH}:/usr/src/project
#                        - ${GRUNT_ADMIN_TARGET_PATH}:/usr/src/project/out/
#                working_dir: /usr/src/project

volumes:
        persistent:

