<div style='color: #000; font-size: 16px; padding:20px 20px; background:#fafafa;'>
    <div align='right' style=''>
        <img width='60' src='http://70e7.com/img/logo.png'>
    </div>


    <div align='left' style='padding-left: 20px'>
        Olá <span style='color:#387900'><?= $name ?>,</span><br>
        <p>Obrigado por entrar em contato conosco!<br>Em breve retornaremos seu contato.</p><br>
    </div>


    <div align='right' style='padding: 20px 10px; font-size: 12px;'>
        Equipe 70<span style='color:#387900;'>E7</span><br>
        <a style='color:#387900' href='mailto:atendimento@70e7.com'>atendimento@70e7.com</a><br>
        <a style='color:#387900' href='http://70e7.com'>70e7.com</a><br><br>
    </div>
    <div align='center' style=' width:100%;height: 3px;background:#eeeeee'>
    </div>
    <div align='center' style='padding: 5px; color: #656565;font-size:12px;'>
        <p style='font-size:12px'><br><i>Copyright © 2017 70E7, All rights reserved.</i><br><span>Você está recebendo esse email pois se cadastrou no site da 70E7.<span><br><br><br>
<!--	            // <span style='font-weight: bold;'>Our address is:</span>-->
	            <br>70E7<br>Rio de Janeiro - Petrópolis<br>Brasil</p><br>
    </div>
</div>
</div>