
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">Usuários</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a class="btn btn-sm btn-outline-secondary" href="<?= URL_ADMIN ?>usuarios/adicionar">
            <span data-feather="plus"></span> Adicionar
        </a>
    </div>
</div>
    <table id="data-table" class="table table-striped table-bordered data-table" style="width:100%">
        <thead>
        <tr>

            <th>Nome</th>
            <th>Email</th>
            <th>Username</th>
            <th>Data de inicio</th>
            <th>Status</th>
            <th class="wactions">Ações</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($usuarios as $info): ?>

            <tr>
                <td><?= $info->name ?></td>
                <td><?= $info->email ?></td>
                <td><?= $info->username ?></td>
                <td><?= $info->date_initiated ?></td>
                <td><?= $info->status ?></td>

                <td class='wactions'>

                    <!-- VISUALIZAR -->
                    <a title='visualizar' href='<?= URL_ADMIN ?>usuarios/visualizar/<?= $info->id_admin_users ?>' class='btn btn-small btn-primary'>
                        <span data-feather="eye"></span>
                    </a>

                    <!-- EDITAR -->
                    <a title='editar' href='<?= URL_ADMIN ?>usuarios/editar/<?= $info->id_admin_users ?>' class='btn btn-small btn-success'>
                        <span data-feather="edit"></span>
                    </a>

                    <!-- EXCLUIR -->
                    <a id="del_<?= $info->id_admin_users ?>" title='excluir' data='<?= URL_ADMIN ?>usuarios/delete/<?= $info->id_admin_users ?>' onclick="del(this.id)" class='btn btn-small btn-danger'>
                        <span data-feather="delete"></span>
                    </a>
                </td>


            </tr>

        <?php endforeach; ?>

        </tbody>
    </table>
















