
<?php
    $labelPage = RedirectHelper::getCurrentAction() == 'adicionar'? "Adicionar": "Editar";
//    $erro = "erro adcionar";
    if(isset($erro)){
        $msg = '<div class="alert alert-danger" role="alert">';
        $msg .= $erro;
        $msg .= '</div>';
        echo $msg;
    }
?>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2"><?= $labelPage ?> usuário</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
<!--        <a class="btn btn-sm btn-outline-secondary" href="--><?//= URL_ADMIN ?><!--usuarios">-->
<!--            <span data-feather="chevron-left"></span> Voltar-->
<!--        </a>-->
    </div>
</div>
<div class="row justify-content-center content-form">
    <div class="col-md-8">
        <h4 class="mb-3">Personal data</h4>
        <form class="needs-validation" novalidate action="<?= URL_ADMIN ?>usuarios/<?= RedirectHelper::getCurrentAction() == 'adicionar'? "adicionar": "editar/". $usuario->id_admin_users ?>" method="POST" enctype="multipart/form-data">
            <div class="mb-3">
                <label for="firstName">Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="" value="<?= $usuario->name ?>">
                <div class="invalid-feedback">
                    Valid first name is required.
                </div>
            </div>

            <div class="mb-3">
                <label for="username">Username</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">@</span>
                    </div>
                    <input type="text" class="form-control" id="username" name="username" placeholder="Username" value="<?= $usuario->username ?>">
                    <div class="invalid-feedback" style="width: 100%;">
                        Your username is required.
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <label for="email">Email <span class="text-muted">(Optional)</span></label>
                <input type="email" class="form-control" id="email" name="email" placeholder="you@example.com" value="<?= $usuario->email ?>">
                <div class="invalid-feedback">
                    Please enter a valid email address for shipping updates.
                </div>
            </div>

            <hr class="mb-4">

            <h4 class="mb-3">Security</h4>



            <div class="row">
<!--                --><?php
//                    if(RedirectHelper::getCurrentAction() == "editar"):
//                ?>
<!--                    <div class="col-md-12 mb-3">-->
<!--                        <label for="cc-name">Current password</label>-->
<!--                        <input type="password" class="form-control" id="cc-name" name="currentpassword" placeholder="">-->
<!--                        <div class="invalid-feedback">-->
<!--                            Name on card is required-->
<!--                        </div>-->
<!--                    </div>-->
<!--                --><?php
//                    endif;
//                ?>

                <?php if(RedirectHelper::getCurrentAction() == "adicionar"): ?>
                    <div class="col-md-6 mb-3">
                        <label for="cc-name">Password</label>
                        <input type="password" class="form-control" id="cc-name" name="password" placeholder="">
                        <small class="text-muted">At least 4 characters.</small>
                        <div class="invalid-feedback">
                            Name on card is required
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="cc-number">Confirm password</label>
                        <input type="password" class="form-control" id="cc-number" name="c_password" placeholder="">
                        <div class="invalid-feedback">
                            Credit card number is required
                        </div>
                    </div>
                <?php endif; ?>


            </div>


            <hr class="mb-4">
            <div class="row justify-content-end">
                <div class=" col-md">
                    <button class="btn btn-70e7 btn-lg float-right" type="submit"><?= $labelPage ?></button>
                </div>
            </div>

        </form>
    </div>
</div>