

<div class='vendas'>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2"><?= $labelPage ?> Usuário</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <!--        <a class="btn btn-sm btn-outline-secondary" href="--><?//= URL_ADMIN ?><!--usuarios">-->
            <!--            <span data-feather="chevron-left"></span> Voltar-->
            <!--        </a>-->
        </div>
    </div>
    <?php if(isset($status)) echo "<div class='well well-large'><center>" . $status . "</center></div>"; ?>

    <div class='row  justify-content-center'>
        <div class='col-md-8'>
            <div class='x_panel'>
                <div class='x_title'>
                    <h4>Dados Cadastrais</h4>
                    <div class='clearfix'></div>
                </div>
                <div class='x_content'>
                    <div class='row dados'>
                        <div class='col-xs-12 col-sm-4'>
                            <infos>
                                <strong>Nome:</strong> <?= $user->name ?><br>
                                <strong>Username:</strong> <?= $user->username ?><br>
                                <strong>Email:</strong> <?= $user->email ?><br>
                            </infos>
                        </div>
                        <div class='col-xs-12 col-sm-4'>
                            <status><strong>Status:</strong> <?= $user->status ?></status>
                        </div>
                        <div class='col-xs-12 col-sm-4'>
                            <data>
                                <strong>Data de cadastro:</strong> <?= $user->date_initiated ?><br>
                            </data>
                        </div>
                    </div>
                    <div class='x_title'>
                        <hr>
                        <h4>Histórico de acessos</h4>
                        <div class='clearfix'></div>
                    </div>
                    <div class='row lista'>
                        <div class="col-sm-12">
                            <table class="table table_user table-striped table-bordered">
                                <thead>
                                <tr role='row'>
                                    <th>Data</th>
                                    <th>Hora</th>
                                    <th>IP</th>
                                    <th>Dispositivo</th>
                                    <th>Browser</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($history as $h): ?>

                                    <tr>
                                        <td><?= $h->date ?></td>
                                        <td><?= $h->time ?></td>
                                        <td><?= $h->user_ip ?></td>
                                        <td><?= $h->user_os ?></td>
                                        <td><?= $h->user_browser ?></td>
                                    </tr>

                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>


</div>

