  <!DOCTYPE html>
  <html class="no-js" lang="pt-br">

      <head>
          <title>Framework 70E7 - <?= ucfirst(RedirectHelper::getCurrentController()) ?> <?= ucfirst(RedirectHelper::getCurrentAction()) ?></title>

          <meta charset="UTF-8"/>
          <meta name="viewport" content="width=device-width, initial-scale=1"/>

          <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">

          <!-- CSS -->
          <link rel="stylesheet" type="text/css" href="<?= CSS ?>style.css" />

          <link rel="apple-touch-icon" sizes="57x57" href="<?= IMG ?>favicon/apple-icon-57x57.png">
          <link rel="apple-touch-icon" sizes="60x60" href="<?= IMG ?>favicon/apple-icon-60x60.png">
          <link rel="apple-touch-icon" sizes="72x72" href="<?= IMG ?>favicon/apple-icon-72x72.png">
          <link rel="apple-touch-icon" sizes="76x76" href="<?= IMG ?>favicon/apple-icon-76x76.png">
          <link rel="apple-touch-icon" sizes="114x114" href="<?= IMG ?>favicon/apple-icon-114x114.png">
          <link rel="apple-touch-icon" sizes="120x120" href="<?= IMG ?>favicon/apple-icon-120x120.png">
          <link rel="apple-touch-icon" sizes="144x144" href="<?= IMG ?>favicon/apple-icon-144x144.png">
          <link rel="apple-touch-icon" sizes="152x152" href="<?= IMG ?>favicon/apple-icon-152x152.png">
          <link rel="apple-touch-icon" sizes="180x180" href="<?= IMG ?>favicon/apple-icon-180x180.png">
          <link rel="icon" type="image/png" sizes="192x192"  href="<?= IMG ?>favicon/android-icon-192x192.png">
          <link rel="icon" type="image/png" sizes="32x32" href="<?= IMG ?>favicon/favicon-32x32.png">
          <link rel="icon" type="image/png" sizes="96x96" href="<?= IMG ?>favicon/favicon-96x96.png">
          <link rel="icon" type="image/png" sizes="16x16" href="<?= IMG ?>favicon/favicon-16x16.png">


          <script src="https://www.google.com/recaptcha/api.js?render=6Ldd5esZAAAAAEQEGA8Se9ioFYJQMpoXI9O0ufgH"></script>


          <script src="https://kit.fontawesome.com/d0ea4f12b0.js" crossorigin="anonymous"></script>
          <script async src="https://www.googletagmanager.com/gtag/js?id=UA-115170112-1"></script>
          <script>
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());

              gtag('config', 'UA-115170112-1');
          </script>
      </head>


      <loader>
          <style type="text/css">
              #preload
              {
                  display: block;
              }
              #posload
              {
                  display: none;
              }
              .sk-circle {
                  margin: 100px auto;
                  width: 40px;
                  height: 40px;
                  position: relative;
              }
              .sk-circle .sk-child {
                  width: 100%;
                  height: 100%;
                  position: absolute;
                  left: 0;
                  top: 0;
              }
              .sk-circle .sk-child:before {
                  content: '';
                  display: block;
                  margin: 0 auto;
                  width: 15%;
                  height: 15%;
                  background-color: #3f7600;
                  border-radius: 100%;
                  -webkit-animation: sk-circleBounceDelay 1.2s infinite ease-in-out both;
                  animation: sk-circleBounceDelay 1.2s infinite ease-in-out both;
              }
              .sk-circle .sk-circle2 {
                  -webkit-transform: rotate(30deg);
                  -ms-transform: rotate(30deg);
                  transform: rotate(30deg); }
              .sk-circle .sk-circle3 {
                  -webkit-transform: rotate(60deg);
                  -ms-transform: rotate(60deg);
                  transform: rotate(60deg); }
              .sk-circle .sk-circle4 {
                  -webkit-transform: rotate(90deg);
                  -ms-transform: rotate(90deg);
                  transform: rotate(90deg); }
              .sk-circle .sk-circle5 {
                  -webkit-transform: rotate(120deg);
                  -ms-transform: rotate(120deg);
                  transform: rotate(120deg); }
              .sk-circle .sk-circle6 {
                  -webkit-transform: rotate(150deg);
                  -ms-transform: rotate(150deg);
                  transform: rotate(150deg); }
              .sk-circle .sk-circle7 {
                  -webkit-transform: rotate(180deg);
                  -ms-transform: rotate(180deg);
                  transform: rotate(180deg); }
              .sk-circle .sk-circle8 {
                  -webkit-transform: rotate(210deg);
                  -ms-transform: rotate(210deg);
                  transform: rotate(210deg); }
              .sk-circle .sk-circle9 {
                  -webkit-transform: rotate(240deg);
                  -ms-transform: rotate(240deg);
                  transform: rotate(240deg); }
              .sk-circle .sk-circle10 {
                  -webkit-transform: rotate(270deg);
                  -ms-transform: rotate(270deg);
                  transform: rotate(270deg); }
              .sk-circle .sk-circle11 {
                  -webkit-transform: rotate(300deg);
                  -ms-transform: rotate(300deg);
                  transform: rotate(300deg); }
              .sk-circle .sk-circle12 {
                  -webkit-transform: rotate(330deg);
                  -ms-transform: rotate(330deg);
                  transform: rotate(330deg); }
              .sk-circle .sk-circle2:before {
                  -webkit-animation-delay: -1.1s;
                  animation-delay: -1.1s; }
              .sk-circle .sk-circle3:before {
                  -webkit-animation-delay: -1s;
                  animation-delay: -1s; }
              .sk-circle .sk-circle4:before {
                  -webkit-animation-delay: -0.9s;
                  animation-delay: -0.9s; }
              .sk-circle .sk-circle5:before {
                  -webkit-animation-delay: -0.8s;
                  animation-delay: -0.8s; }
              .sk-circle .sk-circle6:before {
                  -webkit-animation-delay: -0.7s;
                  animation-delay: -0.7s; }
              .sk-circle .sk-circle7:before {
                  -webkit-animation-delay: -0.6s;
                  animation-delay: -0.6s; }
              .sk-circle .sk-circle8:before {
                  -webkit-animation-delay: -0.5s;
                  animation-delay: -0.5s; }
              .sk-circle .sk-circle9:before {
                  -webkit-animation-delay: -0.4s;
                  animation-delay: -0.4s; }
              .sk-circle .sk-circle10:before {
                  -webkit-animation-delay: -0.3s;
                  animation-delay: -0.3s; }
              .sk-circle .sk-circle11:before {
                  -webkit-animation-delay: -0.2s;
                  animation-delay: -0.2s; }
              .sk-circle .sk-circle12:before {
                  -webkit-animation-delay: -0.1s;
                  animation-delay: -0.1s; }

              @-webkit-keyframes sk-circleBounceDelay {
                  0%, 80%, 100% {
                      -webkit-transform: scale(0);
                      transform: scale(0);
                  } 40% {
                        -webkit-transform: scale(1);
                        transform: scale(1);
                    }
              }

              @keyframes sk-circleBounceDelay {
                  0%, 80%, 100% {
                      -webkit-transform: scale(0);
                      transform: scale(0);
                  } 40% {
                        -webkit-transform: scale(1);
                        transform: scale(1);
                    }
              }
          </style>
          <script type="text/javascript">
              function carregado(){
                  document.getElementById("posload").style.display = "block";
                  document.getElementById("preload").style.display = "none";
              }
          </script>

      </loader>


      <body data-path="<?=URL?>" onload='carregado()'>
          <div id="preload">
              <div class="sk-circle">
                  <div class="sk-circle1 sk-child"></div>
                  <div class="sk-circle2 sk-child"></div>
                  <div class="sk-circle3 sk-child"></div>
                  <div class="sk-circle4 sk-child"></div>
                  <div class="sk-circle5 sk-child"></div>
                  <div class="sk-circle6 sk-child"></div>
                  <div class="sk-circle7 sk-child"></div>
                  <div class="sk-circle8 sk-child"></div>
                  <div class="sk-circle9 sk-child"></div>
                  <div class="sk-circle10 sk-child"></div>
                  <div class="sk-circle11 sk-child"></div>
                  <div class="sk-circle12 sk-child"></div>
              </div>
          </div>

          <div id="posload">
              <nav class="navbar navbar-expand-lg navbar-light">
                  <a class="navbar-brand" href="<?=URL?>home">
                      <img class="logo" src="<?=IMG?>logo_grande.png" width="60">

                  </a>


                  <div class="nav">

                      <a class="nav-link" <?= (RedirectHelper::getCurrentController() != "home") ? "href='".URL."home#company'" : "onclick=\"scrolPagina('company')\"" ?>>Empresa</a>
                      <a class="nav-link" <?= (RedirectHelper::getCurrentController() != "home") ? "href='".URL."home#services'" : "onclick=\"scrolPagina('services')\"" ?>>Serviços</a>
                      <a class="nav-link <?= (RedirectHelper::getCurrentController() == "projetos") ? "active" : "" ?>" href="<?=URL?>projetos">Projetos</a>
                      <a class="nav-link" <?= (RedirectHelper::getCurrentController() != "home") ? "href='".URL."home#contact'" : "onclick=\"scrolPagina('contact')\"" ?>>Contato</a>
                  </div>
              </nav>

              <main role="main" class="">
                  {conteudo}
              </main>

              <footer>

              </footer>
          </div>


          <script
                  src="https://code.jquery.com/jquery-3.5.1.min.js"
                  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
                  crossorigin="anonymous"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
          <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
          <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>


          <script src="<?= JS ?>site.min.js"></script>
      </body>
  </html>


