  <!DOCTYPE html>
  <html class="no-js" lang="pt-br">

      <head>
          <title>Framework 70e7</title>

          <meta charset="UTF-8"/>
          <meta name="viewport" content="width=device-width, initial-scale=1"/>

          <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>

          <!-- CSS -->
          <link rel="stylesheet" type="text/css" href="<?= CSS ?>style.css" />

      </head>




      <body>
          <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">

          </nav>

          <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
              {conteudo}
          </main>

          <footer>


          </footer>


          <script src="<?= JS ?>site.min.js"></script>
      </body>
  </html>


  <!-- Icons -->
  <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
  <script>
      feather.replace()
  </script>


</html>
