  <!DOCTYPE html>
  <html class="no-js" lang="pt-br">

      <head>
          <title>Admin 70E7</title>

          <meta charset="UTF-8"/>
          <meta name="viewport" content="width=device-width, initial-scale=1"/>

          <!-- <link href='https://fonts.googleapis.com/css?family=Patua+One' rel='stylesheet' type='text/css'> -->
          <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
          <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"> -->



          <!-- CSS -->
          <link rel="stylesheet" type="text/css" href="<?= CSS ?>style.css" />

          <link rel="apple-touch-icon" sizes="57x57" href="<?= IMG ?>favicon/apple-icon-57x57.png">
          <link rel="apple-touch-icon" sizes="60x60" href="<?= IMG ?>favicon/apple-icon-60x60.png">
          <link rel="apple-touch-icon" sizes="72x72" href="<?= IMG ?>favicon/apple-icon-72x72.png">
          <link rel="apple-touch-icon" sizes="76x76" href="<?= IMG ?>favicon/apple-icon-76x76.png">
          <link rel="apple-touch-icon" sizes="114x114" href="<?= IMG ?>favicon/apple-icon-114x114.png">
          <link rel="apple-touch-icon" sizes="120x120" href="<?= IMG ?>favicon/apple-icon-120x120.png">
          <link rel="apple-touch-icon" sizes="144x144" href="<?= IMG ?>favicon/apple-icon-144x144.png">
          <link rel="apple-touch-icon" sizes="152x152" href="<?= IMG ?>favicon/apple-icon-152x152.png">
          <link rel="apple-touch-icon" sizes="180x180" href="<?= IMG ?>favicon/apple-icon-180x180.png">
          <link rel="icon" type="image/png" sizes="192x192"  href="<?= IMG ?>favicon/android-icon-192x192.png">
          <link rel="icon" type="image/png" sizes="32x32" href="<?= IMG ?>favicon/favicon-32x32.png">
          <link rel="icon" type="image/png" sizes="96x96" href="<?= IMG ?>favicon/favicon-96x96.png">
          <link rel="icon" type="image/png" sizes="16x16" href="<?= IMG ?>favicon/favicon-16x16.png">


      </head>




      <body data-path='<?=URL_ADMIN?>'>
          <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
              <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#"><?= $_SESSION['user']['name'] ?></a>
        <!--      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">-->
              <ul class="navbar-nav px-3">
                  <li class="nav-item text-nowrap">
                      <a class="nav-link" href="<?= URL_ADMIN ?>home/logout">Sair</a>
                  </li>
              </ul>
          </nav>
          <div class="container-fluid">
              <div class="row">
                  <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                      <div class="sidebar-sticky">
                          <ul class="nav flex-column">
                              <li class="nav-item">
                                  <a class="nav-link <?= (RedirectHelper::getCurrentController() == "home") ? "active" : "" ?>" href="<?= URL_ADMIN ?>home">
                                      <span data-feather="home"></span>
                                      Dashboard <span class="sr-only">(current)</span>
                                  </a>
                              </li>

                              <li class="nav-item d-flex justify-content-between align-items-center text-muted pr-3">
                                  <a class="nav-link <?= (RedirectHelper::getCurrentController() == "usuarios") ? "active" : "" ?>" href="<?= URL_ADMIN ?>usuarios">
                                      <span data-feather="users"></span>
                                      Usuarios
                                  </a>
                                  <a class="d-flex align-items-center text-muted" href="<?= URL_ADMIN ?>usuarios/adicionar">
                                      <span data-feather="plus-circle"></span>
                                  </a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link <?= (RedirectHelper::getCurrentController() == "contato") ? "active" : "" ?>" href="<?= URL_ADMIN ?>contato">
                                      <span data-feather="file"></span>
                                      Contatos
                                  </a>
                              </li>
                          </ul>


                      </div>
                  </nav>

          <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
              {conteudo}

          </main>

          <footer>


          </footer>





                  <script src="<?= JS ?>site.min.js"></script>
      </body>
  </html>


  <!-- Icons -->
  <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
  <script>
      feather.replace()
  </script>



</html>
