<!doctype html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

        <title>Administração</title>

        <!-- CSS -->
        <link rel="stylesheet" type="text/css" href="<?= CSS ?>style.css" />
        <link rel="stylesheet" type="text/css" href="<?= CSS ?>signin.css" />
    </head>

    <body class="text-center">

        {conteudo}

    </body>
</html>